image: node:latest

cache:
  key: node_modules
  paths:
    - node_modules

stages:
  - mirror_github
  - install
  - build
  - deploy

mirror_github:
  stage: mirror_github
  image: ubuntu:18.04
  before_script:
    - apt-get update -y && apt-get install openssh-client -y
    - apt install git -y
    - eval $(ssh-agent -s)
    - echo "$GIT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $GIT_LAB_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.name "${GIT_USER_NAME}"
    - git config --global user.email "${GIT_USER_EMAIL}"
    - ssh "git@$GIT_LAB_HOST"
  script:
    - echo $SOURCE_REPOSITORY
    - git clone --mirror $SOURCE_REPOSITORY Your_Repo_folder_name
    - cd Your_Repo_folder_name
    - git remote remove origin
    - git remote add origin $DESTINATION_REPOSITORY
    - git push --prune --all
    - git push --prune --tags
  only:
    - branches

install:
  stage: install
  only:
    - master
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  only:
    - master
  script:
    - yarn build:production
  dependencies:
    - install
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - master
  script:
    - yarn global add firebase-tools --cache-folder node_modules
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY --project $FIREBASE_PROJECT
  dependencies:
    - install
    - build
