language: node_js
node_js:
  - "10.15"
branches:
  only:
  - development # auto build and deploy in only development branch
  - master # auto build and deploy in only master branch
install:
  - npm install -g firebase-tools # install firebase-cli
  - yarn

script:
  - yarn lint
  - yarn build:production
after_success:
- firebase use --token ${FIREBASE_TOKEN} # set firebase token
- firebase use --add ${PROJECT_ID} # set current project
- firebase deploy --non-interactive --token "${FIREBASE_TOKEN}" # deploy project